### ISSUE TITLE
Bump Gradle and AGP versions

### ISSUE THREAD

**Issue by yshrsmz** [yshrsmz/BuildKonfig#173]
According to the KMP plugin version compatibility table, Kotlin 2.0.21 is fully compatible with Gradle 8.6 and AGP 8.5. So, let's upgrade these plugins

https://kotlinlang.org/docs/multiplatform-compatibility-guide.html#version-compatibility

**Comment by RyuNen344** [comment]
# Milestone
- [ ] bump AGP to 8.5
  - [ ] support KGP 2.0 API changes
- [ ] bump gradle 8.10 or latest
- [ ] bump AGP to 8.8 or latest
  - [ ] support AGP API changes

**Comment by RyuNen344** [comment]
done 🚀
